// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		Account:           newAccount(db, opts...),
		Category:          newCategory(db, opts...),
		Link:              newLink(db, opts...),
		PrismaMigration:   newPrismaMigration(db, opts...),
		Session:           newSession(db, opts...),
		User:              newUser(db, opts...),
		VerificationToken: newVerificationToken(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Account           account
	Category          category
	Link              link
	PrismaMigration   prismaMigration
	Session           session
	User              user
	VerificationToken verificationToken
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		Account:           q.Account.clone(db),
		Category:          q.Category.clone(db),
		Link:              q.Link.clone(db),
		PrismaMigration:   q.PrismaMigration.clone(db),
		Session:           q.Session.clone(db),
		User:              q.User.clone(db),
		VerificationToken: q.VerificationToken.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		Account:           q.Account.replaceDB(db),
		Category:          q.Category.replaceDB(db),
		Link:              q.Link.replaceDB(db),
		PrismaMigration:   q.PrismaMigration.replaceDB(db),
		Session:           q.Session.replaceDB(db),
		User:              q.User.replaceDB(db),
		VerificationToken: q.VerificationToken.replaceDB(db),
	}
}

type queryCtx struct {
	Account           *accountDo
	Category          *categoryDo
	Link              *linkDo
	PrismaMigration   *prismaMigrationDo
	Session           *sessionDo
	User              *userDo
	VerificationToken *verificationTokenDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Account:           q.Account.WithContext(ctx),
		Category:          q.Category.WithContext(ctx),
		Link:              q.Link.WithContext(ctx),
		PrismaMigration:   q.PrismaMigration.WithContext(ctx),
		Session:           q.Session.WithContext(ctx),
		User:              q.User.WithContext(ctx),
		VerificationToken: q.VerificationToken.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
