// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLink = "link"

// Link mapped from table <link>
type Link struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Icon        string    `gorm:"column:icon;not null" json:"icon"`
	URL         string    `gorm:"column:url;not null" json:"url"`
	Title       string    `gorm:"column:title;not null" json:"title"`
	Description string    `gorm:"column:description;not null" json:"description"`
	Rank        int32     `gorm:"column:rank" json:"rank"`
	Public      bool      `gorm:"column:public;not null;default:true" json:"public"`
	Status      int32     `gorm:"column:status;not null;default:1" json:"status"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Cid         string    `gorm:"column:cid;not null" json:"cid"`
}

// TableName Link's table name
func (*Link) TableName() string {
	return TableNameLink
}
