// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSession = "sessions"

// Session mapped from table <sessions>
type Session struct {
	ID           string    `gorm:"column:id;primaryKey" json:"id"`
	SessionToken string    `gorm:"column:sessionToken;not null" json:"sessionToken"`
	UserID       string    `gorm:"column:userId;not null" json:"userId"`
	Expires      time.Time `gorm:"column:expires;not null" json:"expires"`
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
