// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVerificationToken = "verification_tokens"

// VerificationToken mapped from table <verification_tokens>
type VerificationToken struct {
	Identifier string    `gorm:"column:identifier;not null" json:"identifier"`
	Token      string    `gorm:"column:token;not null" json:"token"`
	Expires    time.Time `gorm:"column:expires;not null" json:"expires"`
}

// TableName VerificationToken's table name
func (*VerificationToken) TableName() string {
	return TableNameVerificationToken
}
