// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAccount = "accounts"

// Account mapped from table <accounts>
type Account struct {
	ID                    string    `gorm:"column:id;primaryKey" json:"id"`
	UserID                string    `gorm:"column:userId;not null" json:"userId"`
	Type                  string    `gorm:"column:type;not null" json:"type"`
	Provider              string    `gorm:"column:provider;not null" json:"provider"`
	ProviderAccountID     string    `gorm:"column:providerAccountId;not null" json:"providerAccountId"`
	RefreshToken          string    `gorm:"column:refresh_token" json:"refresh_token"`
	AccessToken           string    `gorm:"column:access_token" json:"access_token"`
	ExpiresAt             int32     `gorm:"column:expires_at" json:"expires_at"`
	RefreshTokenExpiresIn int32     `gorm:"column:refresh_token_expires_in" json:"refresh_token_expires_in"`
	TokenType             string    `gorm:"column:token_type" json:"token_type"`
	Scope                 string    `gorm:"column:scope" json:"scope"`
	IDToken               string    `gorm:"column:id_token" json:"id_token"`
	SessionState          string    `gorm:"column:session_state" json:"session_state"`
	CreatedAt             time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt             time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
